Donor/Donor/Models/CheckUp.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckUp
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}

Donor/Donor/Controllers/CheckUpsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Donor.Models;

namespace Donor.Controllers
{
    public class CheckUpsController : Controller
    {
        private DonorEntities db = new DonorEntities();

        // GET: CheckUps
        
        public ActionResult Index()
        {
            //var checkUps = db.CheckUps.Include(c => c.Hospital);
            string email = User.Identity.Name;
            //List<Hospital>  h = db.Hospitals.Where(a => a.EmailID.Equals(email)).ToList<Hospital>();
            return View(db.CheckUps.Where(a=>a.Hospital.EmailID.Equals(email)).ToList());
            
        }

        // GET: CheckUps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckUp checkUp = db.CheckUps.Find(id);
            if (checkUp == null)
            {
                return HttpNotFound();
            }
            return View(checkUp);
        }

        // GET: CheckUps/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.HospitalId = new SelectList(db.Hospitals, "HospitalID", "HospitalName");
            return View();
        }

        // POST: CheckUps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "Id,Email,HospitalId,State,City")] CheckUp checkUp)
        {
            bool Status = false;
            string message = "";
            if (ModelState.IsValid)
            {
                var isExist = IsEmailExist(checkUp.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "You Already Applied for Checkup");
                    ViewBag.HospitalId = new SelectList(db.Hospitals, "HospitalID", "HospitalName", checkUp.HospitalId);
                    return View(checkUp);
                }
                else
                {
                    db.CheckUps.Add(checkUp);
                    db.SaveChanges();
                    Status = true;
                    ViewBag.HospitalId = new SelectList(db.Hospitals, "HospitalID", "HospitalName", checkUp.HospitalId);
                    message = "You have successfully applied for Checkup and You will receive a Email from the corresponding hospital to your registered mail id"+checkUp.Email;
                }
                ViewBag.Message = message;
                ViewBag.Status = Status;
                return View(checkUp);
            }

           
            return View(checkUp);
        }

        // GET: CheckUps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckUp checkUp = db.CheckUps.Find(id);
            if (checkUp == null)
            {
                return HttpNotFound();
            }
            ViewBag.HospitalId = new SelectList(db.Hospitals, "HospitalID", "HospitalName", checkUp.HospitalId);
            return View(checkUp);
        }

        // POST: CheckUps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,HospitalId,State,City")] CheckUp checkUp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkUp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HospitalId = new SelectList(db.Hospitals, "HospitalID", "HospitalName", checkUp.HospitalId);
            return View(checkUp);
        }

        // GET: CheckUps/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    CheckUp checkUp = db.CheckUps.Find(id);
        //    if (checkUp == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(checkUp);
        //}

        // POST: CheckUps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckUp checkUp = db.CheckUps.Find(id);
            db.CheckUps.Remove(checkUp);
            db.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully", JsonRequestBehavior.AllowGet });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public bool IsEmailExist(string emailID)
        {
            using (DonorEntities dc = new DonorEntities())
            {
                var v = dc.CheckUps.Where(a => a.Email == emailID).FirstOrDefault();
                return v != null;
            }
        }

    [HttpPost]
        public ActionResult SendEmail(int id)
        {
            string emailID = "";
            var email = db.CheckUps.Find(id);
            emailID = email.Email;
            string location = email.City;
            var fromEmail = new MailAddress("organdonante@gmail.com", "Organ Donante");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "helloworld123#"; // Replace with actual password
            string subject = "";
            string body = "";
           
                subject = "Your Appointment Scheduled for Master Health Checkup";

                body = " You can visit hospital at 9Am at "+location;
            
           


            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
            return Json(new { sucess = emailID }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

Donor/Donor/Controllers/DonorDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Donor.Models;

namespace Donor.Controllers
{
    public class DonorDetailsController : Controller
    {
        private DonorEntities db = new DonorEntities();

        // GET: DonorDetails
        [Authorize]
        public ActionResult ReadOnly()
        {
            return View();
        }
        public ActionResult Index()
        {
            return PartialView();
        }

        // GET: DonorDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonorDetail donorDetail = db.DonorDetails.Find(id);
            if (donorDetail == null)
            {
                return HttpNotFound();
            }
            return View(donorDetail);
        }

        // GET: DonorDetails/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: DonorDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude  = "IsHospitalAuthorized")] DonorDetail donorDetail)
        {
            bool Status = false;
            string message = "";

            if (ModelState.IsValid)
            {
                donorDetail.IsHospitalAuthorized = false;
                var isExist = IsEmailExist(donorDetail.DonorEmail);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "You are already an donor");
                    return View(donorDetail);
                }
                else
                {
                    db.DonorDetails.Add(donorDetail);
                    db.SaveChanges();
                    sendEmail(donorDetail.DonorEmail);
                    message = "Registration successfully done for LifeLinker please complete the check up process in any one of the hospital registered under lifelinker.You will receive an Email about the checkup " +
                       " has been sent to your email id:" + donorDetail.DonorEmail;
                    Status = true;
                }
                
                
                
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(donorDetail);
        }

        // GET: DonorDetails/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonorDetail donorDetail = db.DonorDetails.Find(id);
            if (donorDetail == null)
            {
                return HttpNotFound();
            }
            return View(donorDetail);
        }

        // POST: DonorDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       
        public ActionResult Edit([Bind(Include = "DonorId,DonorName,DonorAddress,DonorEmail,DonorMobile,DonorGender,OrganName,IsHospitalAuthorized")] DonorDetail donorDetail)
        {
            
                db.Entry(donorDetail).State = EntityState.Modified;
                db.SaveChanges();
            return RedirectToAction("Index");
            
            
        }

        // GET: DonorDetails/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DonorDetail donorDetail = db.DonorDetails.Find(id);
        //    if (donorDetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(donorDetail);
        //}

        // POST: DonorDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        
        public ActionResult DeleteConfirmed(int id)
        {
            DonorDetail donorDetail = db.DonorDetails.Find(id);
            db.DonorDetails.Remove(donorDetail);
            db.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" ,JsonRequestBehavior.AllowGet});
        }

        public ActionResult GetData()
        {
            List<DonorDetail> donorList = db.DonorDetails.ToList<DonorDetail>();
            return Json(new { data = donorList }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDataForUsersView()
        {
            
            return Json(new { data = db.DonorDetails.Where(a=>(Boolean)a.IsHospitalAuthorized==true) }, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (DonorEntities dc = new DonorEntities())
            {
                var v = dc.DonorDetails.Where(a => a.DonorEmail == emailID).FirstOrDefault();
                return v != null;
            }
        }

        [NonAction]
        public void sendEmail(string emailID)
        {
            var verifyUrl = "/CheckUps/Create";
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("organdonante@gmail.com", "Organ Donante");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = "helloworld123#"; // Replace with actual password
            string subject = "";
            string body = "";
            
                subject = "Hurray You have Successfully Registered Life Linker";

                body = "<br/><br/>We are excited to tell you that your Application for life linker is received and it is under process you will become a successfull life linker after the successfull completion of hospital checkup with in 1 month other wise your account will be deleted" +
                    " Please Click on the below link for the hospital checkup" +
                    " <br/><br/><a href='" + link + "'>" + link + "</a> ";
          


            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }

    }
}

Donor/Donor/Views/CheckUps/Delete.cshtml
@model Donor.Models.CheckUp

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheckUp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospital.HospitalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospital.HospitalName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Donor/Donor/Views/CheckUps/Details.cshtml
@model Donor.Models.CheckUp

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CheckUp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hospital.HospitalName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hospital.HospitalName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Donor/Donor/Views/CheckUps/Edit.cshtml
@model Donor.Models.CheckUp

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckUp</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HospitalId, "HospitalId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("HospitalId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.HospitalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Donor/Donor/Views/CheckUps/Index.cshtml
@model IEnumerable<Donor.Models.CheckUp>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CheckUp Records</h2>
<a class='btn btn-primary btn-sm' href='@Url.Action("Index","DonorDetails")'>Donors</a>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hospital.HospitalName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hospital.HospitalName)
            </td>
            <td>
                <a class='btn btn-primary btn-sm' onclick="SendEmail(@item.Id)">SendEmail</a>
                @*<a class='btn btn-danger btn-sm' onclick="Delete(@item.Id)">Delete</a>*@
            </td>
        </tr>
    }

</table>

@section scripts{

    <script>
         function SendEmail(id) {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SendEmail", "CheckUps")/' + id,
                    success: function (data) {
                        console.log("Email"+data.success);

                    }

                });

        }
        function Delete(id) {
            if (confirm('Are you sure to Delete this Record?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "CheckUps")/' + id,
                    

                });
            }
        }
    </script>
}

Donor/Donor/Views/CheckUps/SendEmail.cshtml
@{
    ViewBag.Title = "SendEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SendEmail</h2>